#Dracula Theme
#import = ["~/.config/alacritty/dracula.toml"]

#Catpuccin theme
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
   "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
[colors]
draw_bold_text_with_bright_colors = true

[shell]
program = "/usr/bin/zsh"
#args = ["-l","-c","tmux attach || tmux"]

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

#[window]
#opacity = 0.95
#blur = true

[cursor]
style = "Beam"

[mouse]
hide_when_typing = true